# Change these first
owner: dherald # Your GitHub organization or username, where this repository lives
repo: service-status # The name of this repository

sites:
  - name: www.deeplol.gg
    url: https://www.deeplol.gg
  - name: b2c-api.deeplol.gg
    url: https://b2c-api.deeplol.gg/live   
  - name: pro.deeplol.gg
    url: https://pro.deeplol.gg
  - name: sogang.dherald.com
    url: https://sogang.dherald.com
  - name: bfmba.ac.kr
    url: https://bfmba.ac.kr/
  - name: ajoumpa.ac.kr
    url: https://ajoumpa.ac.kr/
  - name: frenchmaster.co.kr
    url: https://frenchmaster.co.kr
  - name: japanesemaster.co.kr
    url: https://japanesemaster.co.kr/
  - name: abedu.co.kr
    url: https://abedu.co.kr/
  - name: announcercoach.co.kr
    url: https://announcercoach.co.kr/
  - name: gedpass.co.kr
    url: https://gedpass.co.kr/
  - name: tongdae.com
    url: https://tongdae.com/
  - name: heraldeprep.com
    url: https://heraldeprep.com/
  - name: heraldjob.com
    url: https://heraldjob.com/
  - name: ktigers.org
    url: https://ktigers.org/
  - name: ptepass.co.kr
    url: https://ptepass.co.kr/
  - name: heraldstudy.com
    url: https://heraldstudy.com/
  - name: heraldtrans.com
    url: https://heraldtrans.com/
  - name: hisacademy.co.kr
    url: https://hisacademy.co.kr/
  - name: hisbook.co.kr
    url: https://hisbook.co.kr/   
  - name: herald.ptea.co.kr
    url: https://herald.ptea.co.kr/
  - name: hisacademy.co.kr
    url: https://hisacademy.co.kr/
  - name: heraldinsight.co.kr
    url: http://heraldinsight.co.kr/    
  - name: heraldtomorrow.co.kr
    url: http://heraldtomorrow.co.kr/        
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: https://dherald.github.io/service-status/
  baseUrl: /service-status
  logoUrl: https://dherald.com/images/logo/top_logo.png
  name: Service Status
  introTitle: "**디지털헤럴드** 서비스 모니터링 및 상태 페이지"
  introMessage: 디지털헤럴드 개발팀
  navbar:
    - title: DHERALD
      href: https://dherald.com
    
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
